export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CHECKOUT = "CHECKOUT";
export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const UPDATE_COUPON_CODE = "UPDATE_COUPON_CODE";
